config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',      to: 'static_pages#help'
  get  '/about',     to: 'static_pages#about'
  get  '/cozmo',     to: 'static_pages#cozmo'
  get  '/sat',       to: 'static_pages#sat'
  get  '/android',   to: 'static_pages#android'
  get  '/qoe',       to: 'static_pages#qoe'
  get  '/rnn',       to: 'static_pages#rnn'
  get  '/beer',      to: 'static_pages#beer'
  get  '/az',        to: 'static_pages#az'
  get  '/vinyl',     to: 'static_pages#vinyl'
  get  '/ar',        to: 'static_pages#ar'
  get  '/ar_tools',  to: 'static_pages#ar_tools'
  get  '/ar_models', to: 'static_pages#ar_models'
  get  '/ar_inter',  to: 'static_pages#ar_inter'
  get  '/deepfake',  to: 'static_pages#deepfake'
  get  '/contact',   to: 'static_pages#contact'
  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "David Weinflash"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
    # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <normal>
    <ul><%= link_to "David Weinflash", asset_path("Weinflash_Resume.pdf") %></ul>
  </normal>
  <nav>
    <ul>
      <%= link_to "About", about_path %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("favicon-512x512.png", size: "32x32"), '/', class: 'navbar-brand' %>
    <%= link_to "David Weinflash", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "GitHub", "https://github.com/dweinflash" %></li>
        <li><%= link_to "LinkedIn", "https://www.linkedin.com/in/dweinflash/" %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h5>
  <center>
    <%= image_tag "headshot.png", :class => "style_image" %>
  </center>
</h5>
<h1>
  About
</h1>
<p>
  Hi! I'm <%= link_to "David", asset_path("Weinflash_Resume.pdf") %>. I'm a data analyst and software engineer currently 
  pursuing a M.S. in Computer Science at UC Santa Barbara. My research interests center around data mining techniques 
  and machine learning, especially as it relates to computer vision and statistical inference. 
  <p>
    Email: david.weinflash [AT] gmail.com
  </p>
</p>

app/views/static_pages/android.html.erb
<% provide(:title, "Android Network Tools") %>
<h1>Android Network Tools</h1>
<h2>Summary</h2>
<p>
  In this project I teamed with the <a href="https://moment.cs.ucsb.edu/">Mobility Management and Networking (MOMENT) Lab</a> 
  at UC Santa Barbara to introduce Edain Mobile, an Android application that provides a set of tools to measure network performance, 
  network speed and web page performance. The intention of Edain Mobile is to evaluate network function in resource constrained 
  environments. The three primary modules in Edain Mobile are <i>Ping</i>, <i>Speed Test</i> and <i>Page Load</i>.
</p>
<center>
  <%= image_tag "android_home.png", :class => "style_image", :size => "200x300" %>
  <%= image_tag "android_ping.png", :class => "style_image", :size => "200x300" %>
  <%= image_tag "android_speed.png", :class => "style_image", :size => "200x300" %>
  <%= image_tag "android_plt.png", :class => "style_image", :size => "200x300" %>
</center>
<center>
  <i>Edain Mobile Modules:</i> Home, Ping, Speed Test <i>&</i> Page Load
</center>
<h2>Ping</h2>
<p>
  The Ping module sends a specified amount of packets to a chosen network host. Results are aggregated in a file (.csv), 
  which may be cleared and re-written using the <i>Clear</i> button. Results may be exported from the application via
  Google Drive using the corresponding <i>Export</i> button.
</p>
<h2>Speed Test</h2>
<p>
  The Speed Test module runs and collects results from <a href="https://www.speedtest.net/">Ookla's Speedtest</a>, testing the 
  speed and performance of the device's internet connection. Tests are run at user-defined intervals (minutes), where class duration 
  is usually 75 minutes and testing interval is typically every 15 minutes. Results are aggregated in a common .csv file 
  and may be cleared or exported via Google Drive using the corresponding <i>Clear</i> and <i>Export</i> buttons.
</p>
<h2>Page Load</h2>
<p>
  The Page Load module utilizes <a href="https://webpagetest.org/">WebPageTest</a> to measure and analyze the performance of web pages. 
  Tests are performed one domain at a time, where test time is limited to a maximum user-defined <i>Timeout Seconds</i>. <i>County</i>, 
  <i>Location</i> and <i>Provider</i> inputs are also required and are stored in the filename of the results file (.csv). All test result 
  files are stored in the device's Download folder.
</p>
<h2>Documents</h2>
<h3>
  <%= link_to image_tag("GitHub.png", size: "90x100", alt: "GitHub"), 'https://github.com/dweinflash/AndroidNetworkTools' %>
</h3>

app/views/static_pages/ar.html.erb
<% provide(:title, "AR") %>
<h1>Augmented Reality</h1>
<h2>Summary</h2>
<p>
  In this project I set out to develop an application that demonstrates augmented reality in a useful setting. Specifically, 
  I experimented with the augmented reality platform <a href="https://developer.apple.com/augmented-reality/">ARKit</a> to develop
  an iOS application that virtually renders wall stud locations in my apartment. I've split the project into three categories – 
  <a href="/ar_tools">Toolkit</a>, <a href="/ar_models">Models</a> and <a href="/ar_inter">Interaction</a> – where each category
  is used to illustrate my first development experience in the world of augmented reality.
</p>
<h3>
  <center>
    <%= image_tag "MagicPlan.gif", :class => "style_image", :size => "500x300" %>
  </center>
</h3>
<h2>Goals</h2>
  <li>Utilize Apple's ARKit to place virtual content at tracked, real-world locations within my apartment.</li>
  <li>Measure and model my apartment with computer-aided design and augmented reality software.</li>
  <li>Create an iOS application that renders virtual wall studs to match the world space in my apartment.</li>
<h2>Takeaways</h2>
  <li>ARKit provides many useful functions to perform world tracking, surface detection and model placement.</li>
  <li><a href="https://www.magicplan.app/">Magicplan</a> uses augmented reality and computer vision effectively to model and export 3D spaces.</li>
  <li>In addition to world tracking, image tracking may be an effective approach to accurately render virtual wall studs.</li>
<h2>Documents</h2>
<h3>
  <%= link_to image_tag("GitHub.png", size: "90x100", alt: "GitHub"), 'https://github.com/dweinflash/AR_StudFinder' %>
</h3>

app/views/static_pages/ar_inter.html.erb
<% provide(:title, "AR:Interaction") %>
<h1>Augmented Reality: Interaction</h1>
<h2>Floorplan Model</h2>
<p>
  To measure the accuracy of my 3D modeling software, I imported and rendered a virtual model onto the walls of
  my apartment's kitchen and living room. Using pan gestures, I then arranged and scaled the model accordingly 
  to match the dimensions of my apartment in the world space. While the model effectively covered the world space, 
  it left a lot to be desired in terms of precision and alignment. Future iterations should explore image tracking in 
  addition to world tracking, aiming for a more realistic virtual model that convincingly snaps to the room walls in view.
</p>
<h3>
  <center>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/2TiGbH3ULl0" frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </center>
</h3>
<center>Floorplan Model: Demo</center>
<h2>Wall Studs Model</h2>
<p>
    Using world tracking and model placement produced a less convincing result for the 3D Wall Studs model than for the 3D
    Floorplan model. Using the ground floor as reference, the 3D model was placed in the world space according to the pivot 
    point attached to bottom of the SceneKit model. As demonstrated, the model follows a vanishing point not aligned with 
    the wall in the world space. Image tracking would be a promising solution for this model, as the model has minimal depth
    and would stick well to a flat plane.
</p>
<h3>
  <center>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/QAHIHzBK3BM" frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </center>
</h3>
<center>Wall Studs Model: Demo</center>

app/views/static_pages/ar_models.html.erb
<% provide(:title, "AR:Models") %>
<h1>Augmented Reality: Models</h1>
<h2>Floorplan</h2>
<p>
  To measure my apartment dimensions I relied on old-fashioned techniques (tape measurer) and innovative computer 
  vision software. In terms of the new technology, I utilized the iOS application <a href="https://www.magicplan.app/">Magicplan</a>
  to construct a 2D and 3D models of my living space. Using the measurements provided by the models, I crafted 3D models of my apartment
  to virtually render wall studs in my iOS ARKit application.
</p>
<center>
  <%= image_tag "ArriveFloorplan.png", :class => "style_image", :size => "450x300" %>
</center>
<center>Apartment Floorplan</center>
<h2>Magicplan</h2>
<p>
  The Magicplan software provided a simple and intuitive application to measure my apartment and create 3D models. Using computer vision in the context 
  of object recognition, Magicplan allows a user to measure a living space by walking around the space and aligning the camera with the room's features. 
  Once finished, Magicplan outputs a 2D floorplan and 3D model of the space, highlighting the dimensions and prominent features in the room.
</p>
<center>
  <%= image_tag "MagicPlan.png", :class => "style_image", :size => "300x300" %>
  <%= image_tag "MagicPlanSCN.png", :class => "style_image", :size => "450x300" %>
</center>
<center>Magicplan: Floorplan & 3D Model</center>
<h3>
  <center>
    <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/PqLijPgLHXg" frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </center>
</h3>
<center>Magicplan: Demo</center>
<h2>Autodesk</h2>
<p>
  Computer-aided design software provided another solution when generating 3D models. In particular, I experimented with the 
  design software <a href="https://www.autodesk.com/products/fusion-360/overview?term=1-YEAR&support=null">Autodesk: Fusion 360</a>
  to generate 3D models that scaled according to the wall space in my apartment's living room. Autodesk provided an intuitive platform 
  with which to build and export 3D models that matched my apartment floorplan.
</p>
<center>
  <%= image_tag "Autodesk.png", :class => "style_image", :size => "450x300" %>
</center>
<center>Autodesk: 3D Model</center>
<h2>SceneKit</h2>
<p>
  In addition to generating models with proprietary software, I also experimented with designing 3D models from within Xcode's
  <a href="https://developer.apple.com/documentation/scenekit/">SceneKit Editor</a>. The SceneKit Editor not only easily imported 
  external models (.obj), converting to the relevant file extension when necessary (.scn), but also offered the tools necessary to 
  design and export custom 3D models. The two figures below demonstrate a model imported into SceneKit from Autodesk and another 
  designed from scratch from within the application.
</p>
<center>
  <%= image_tag "FloorplanSCN.png", :class => "style_image", :size => "450x300" %>
  <%= image_tag "StudsSCN.png", :class => "style_image", :size => "450x300" %>
</center>
<center>SceneKit: Imported & Designed 3D Models</center>

app/views/static_pages/ar_tools.html.erb
<% provide(:title, "AR:Toolkit") %>
<h1>Augmented Reality: Toolkit</h1>
<h2>ARKit</h2>
<p>
  ARKit, a powerful augmented reality framework provided by Apple, allowed me to place virtual content 
  at tracked, real-world locations within my apartment. Once placed, ARKit provided the hand gestures necessary 
  to interact with and scale the virtual content. Ultimately, by using world tracking and ray casting, ARKit convincingly 
  arranged virtual models in my world space and made for a realistic augmented reality experience.
</p>
<center>
  <%= image_tag "coffeecup.png", :class => "style_image", :size => "450x320" %>
</center>
<center>ARKit: Virtual Model</center>
<h2>World Tracking</h2>
<p>
  ARKit uses a world tracking configuration to detect real-world surfaces. In order to establish world tracking, ARKit must 
  first get a sense of perspective. Such a sense of perspective can be established by moving the device's camera throughout
  the world space, using an ARKit interface named <i>ARCoachingOverlayView</i> to instruct the user to explore the physical and
  build a virtual sense of reference.
</p>
<center>
  <%= image_tag "worldtrack.png", :class => "style_image", :size => "320x400" %>
</center>
<center>ARKit: World Tracking</center>
<h2>Focus Square</h2>
<p>
  To get an idea of where to place virtual content in the world space, a focus square is annotated onto the screen. The primary 
  purpose of the focus square is to give a visual confirmation of the shapes, alignments and surfaces detected by ARKit. To detect 
  surfaces, ARKit uses an <i>ARRaycastQuery</i>, defining where the 3D location in the world space exists as a 2D point on the device screen.
</p>
<center>
  <%= image_tag "FocusSquare.png", :class => "style_image", :size => "450x320" %>
</center>
<center>ARKit: Focus Square</center>
<h2>Gestures</h2>
<p>
  A pan gesture recognizer allows users to move virtual content on screen. By clicking and dragging a virtual object, the application 
  calculates the content's orientation information and uses a <i>hit test</i> to refine the position of the object in the world. What 
  results is a refined virtual object that moves across the plane detected by ARKit.
</p>
<h3>
  <center>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/uF0tGEfhltU" frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </center>
</h3>
<center>ARKit: Gestures</center>

app/views/static_pages/az.html.erb
<% provide(:title, "AZ Homes") %>
<h1>Pricing Factors in the Arizona Home Market</h1>
<h2>Summary</h2>
<p>
  In this statistical analysis research project, the Arizona home market was investigated 
  with <a href="https://www.zillow.com/research/data/">Zillow Housing Data</a>,
  <a href="https://www.fbi.gov/services/cjis/ucr">FBI Crime Reporting Data</a> and 
  <a href="https://www.azed.gov/accountability-research">Department of Education Data</a> in order
  to determine 1) the viability of home ownership in Arizona and 2) the most significant factors influencing
  the price of a single family home. By analyzing historical price appreciation in light of socioeconomic 
  factors – school districts, location, crime, etc. – the most significant factors influencing housing cost are
  investigated. Ultimately, this project serves to provide an analytical guide to determine what factors are most
  important to consider when buying a home.
</p>
<h2>
  <center>
    <%= image_tag "AZ_Graph.png", :size => "600x300" %>
  </center>
</h2>
<h2>Goals</h2>
  <li>Compare and contrast Arizona home market with national home market.</li>
  <li>Analyze impactful pricing factors:
    <ul>
      <li>Geography</li>
      <li>Population</li>
      <li>Education</li>
      <li>Crime</li>
    </ul>
  </li>
<h2>Takeaways</h2>
  <li>Larger population does not equate to a higher home value.</li>
  <li>In Arizona, proficiency in English a stronger indicator for higher home values than proficiency in Mathematics.</li>
  <li>Nationwide, a lower violent crime rate is a stronger indicator for higher home values than a lower property crime rate.</li>
<h2>Documents</h2>
<h3>
  <%= link_to image_tag("Slides.png", size: "80x100", alt: "Slides"), asset_path("AZ_Presentation.pdf") %>
  <%= link_to image_tag("PDF.png", size: "80x100", alt: "Report"), asset_path("AZ_Report.pdf") %>
</h3>

app/views/static_pages/beer.html.erb
<% provide(:title, "Beer") %>
<h1>US Craft Beer</h1>
<h2>Summary</h2>
<p>
  In this project I set out to analyze data scraped from the website <a href="https://www.beeradvocate.com/">BeerAdvocate</a> 
  in order to determine what factors make for a great beer. With the help of RStudio and a multiple linear regression model,
  I measure the effectiveness of <i>Style</i>, <i>Alcohol by Volume</i>, <i>Age</i>, <i>Year</i> and <i>Region</i> in predicting a beer's rating.
  After processing and segmenting the data, I plot the highest rated beers in order to illustrate which regions of the United States brew the best beer.
</p>
<center>
  <%= image_tag "Beer_ScoresPerState.png", :class => "style_image", :size => "450x320" %>
  <%= image_tag "Beer_KFold.png", :class => "style_image", :size => "450x320" %>
</center>
<center>
  <i>Beer Rating & Model Validation</i>
</center>
<h2>Goals</h2>
  <li>Pre-process data scraped from <a href="https://www.beeradvocate.com/">BeerAdvocate</a>.</li>
  <ul>
    <li>Analyze only domestic beer.</li>
  </ul>
  <li>Determine which states brew the best beer.</li>
  <li>Fit a multiple linear regression model to predict a beer's rating.</li>
  <ul>
    <li>Use k-fold cross-validation to assess the model.</li>
  </ul>
<h2>Takeaways</h2>
  <li>Highest rated beer found in the Northeast.</li>
  <li>Multiple linear regression model not especially effective.</li>
  <ul>
    <li>Poor goodness of fit (R<sup>2</sup> ~0.14).</li>
    <li>Beer <i>style</i> a significant factor.</li>
  </ul>
  <li>Predicted rating suffers if beer brewed in the West.</li>
<h2>Documents</h2>
<h3>
  <%= link_to image_tag("GitHub.png", size: "90x100", alt: "GitHub"), 'https://github.com/dweinflash/Beer' %>
</h3>

app/views/static_pages/deepfake.html.erb
<% provide(:title, "Deepfakes") %>
<h1>Deepfake Videos</h1>
<h2>Summary</h2>
<p>
  Just as advances in machine learning gave rise to <a href="https://en.wikipedia.org/wiki/Deepfake">deepfake videos</a>, so to can modern machine 
  learning models be put to use to realiably detect fake media content. In this project I set out to do just that – first using deep neural networks 
  to generate deepfake videos, then using neural networks to correctly distinguish between fake and unaltered media content. In each scenario, I 
  test the system on a range of different videos in order to evaluate the effectiveness of the proposed network.
</p>
<h3>
  <center>
    <%= image_tag "Deepfake.gif", :class => "image", :size => "500x200" %>
  </center>
</h3>
<h2>Goals</h2>
  <li>Utilize a generative deep neural network to create deepfake videos.</li>
  <li>Train a neural network architecture to accurately identify deepfake videos.</li>
  <li>Input a variety of altered media content to measure the effectiveness of the proposed systems.</li>
<h2>Takeaways</h2>
  <li>The framework proposed in <a href="https://arxiv.org/abs/2003.00196"><i>First Order Motion Model for Image Animation</i></a> generates 
      convincing deepfake videos.</li>
  <li>The network proposed in <a href="https://arxiv.org/abs/2004.07676"><i>Video Face Manipulation Detection Through Ensemble of CNNs</i></a> 
      consistently identifies fake media content.</li>
  <li>Certain data augmentation operations are able to influence the classification results of the deepfake detection system.</li>
<h2>Documents</h2>
<h3>
  <%= link_to image_tag("Slides.png", size: "80x100", alt: "Slides"), asset_path("Deepfake_Presentation.pdf") %>
  <%= link_to image_tag("PDF.png", size: "80x100", alt: "Report"), asset_path("Deepfake_Report.pdf") %>
  <%= link_to image_tag("GitHub.png", size: "90x100", alt: "GitHub"), 'https://github.com/dweinflash/Deepfakes' %>
</h3>

app/views/static_pages/vinyl.html.erb
<% provide(:title, "Vinyl") %>
<h1>Vinyl Videos</h1>
<h2>Summary</h2>
<p>
  In this project I set out to add a visual component to my record collection. Specifically, I put together 
  a music video file and added lyric subtitles that sync up with the music when played on vinyl. To watch the video while 
  listening to the record, I added the video file to a Raspberry Pi and hooked the Pi up to a video projector, making sure to play 
  the video in time with the needle on the record. The result is a karaoke-style music video projected onto the wall with subtitles 
  displayed in sync with the music on the record.
</p>
<h3>
  <center>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/VKatghcquZU" frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </center>
</h3>
<h2>Goals</h2>
  <li>Create a video with subtitles that match the lyrics on a vinyl record.</li>
  <li>Deploy video to a Raspberry Pi to play wirelessly when music starts.</li>
  <li>Use video projector to watch video while music plays on record.</li>
<h2>Overview</h2>
  <li>Gather all lyrics for the record.</li>
  <li>Use <a href="https://www.apple.com/imovie/">iMovie</a> to compile a music video for the record.</li>
  <li>Use <a href="https://www.apple.com/mac/garageband/">GarageBand</a> to record the vinyl and export the audio file.</li>
  <li>Use the lyrics, audio file and <a href="http://www.lrcgenerator.com/">LRC Generator</a> to create a .lrc file.</li>
  <li>Format the .lrc file as .ass to get a fading subtitles effect.</li>
  <li>Use <a href="https://ffmpeg.org/">FFmpeg</a> to add the .ass subtitles file to the music video file.</li>
<h2>Documents</h2>
<h3>
  <%= link_to image_tag("GitHub.png", size: "90x100", alt: "GitHub"), 'https://github.com/dweinflash/VinylVideos' %>
</h3>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>